spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Yzhang520!

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.imhuis.code.examples.mybatis.entity