spring:
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds1
      username: app_user
      password: Yzhang520!
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds2
      username: app_user
      password: Yzhang520!
